/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PureGym API
 * API for 0-24 gym system
 * OpenAPI spec version: v1
 */

export type AccessResult = (typeof AccessResult)[keyof typeof AccessResult]

export const AccessResult = {
  Granted: 0,
  DeniedExpired: 1,
  DeniedSuspended: 2,
  DeniedNoMembership: 3,
} as const
