/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PureGym API
 * API for 0-24 gym system
 * OpenAPI spec version: v1
 */
import type { MembershipStatus } from './membershipStatus'

export interface AddMembershipResponse {
  membershipId?: string
  memberId?: string
  membershipTypeId?: string
  membershipTypeName?: string
  startDateUtc?: string
  endDateUtc?: string
  status?: MembershipStatus
}
