/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PureGym API
 * API for 0-24 gym system
 * OpenAPI spec version: v1
 */
import type { AccessResult } from './accessResult'
import type { Member } from './member'
import type { Membership } from './membership'

export interface GymAccessLog {
  id?: string
  memberId?: string
  /** @nullable */
  membershipId?: string | null
  accessedAtUtc?: string
  result?: AccessResult
  member?: Member
  membership?: Membership | null
}
