/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PureGym API
 * API for 0-24 gym system
 * OpenAPI spec version: v1
 */
import type { GymAccessLog } from './gymAccessLog'

export interface ListQueryOfGymAccessLog {
  items?: GymAccessLog[]
  totalCount?: number
}
