/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PureGym API
 * API for 0-24 gym system
 * OpenAPI spec version: v1
 */
import type { GymAccessLog } from './gymAccessLog'
import type { Member } from './member'
import type { MembershipStatus } from './membershipStatus'
import type { MembershipType } from './membershipType'

export interface Membership {
  isDeleted?: boolean
  /** @nullable */
  deletedAtUtc?: string | null
  id?: string
  memberId?: string
  membershipTypeId?: string
  startDateUtc?: string
  endDateUtc?: string
  status?: MembershipStatus
  createdAtUtc?: string
  member?: Member
  membershipType?: MembershipType
  accessLogs?: GymAccessLog[]
  daysRemaining?: number
}
