/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PureGym API
 * API for 0-24 gym system
 * OpenAPI spec version: v1
 */
import type { GymAccessLog } from './gymAccessLog'
import type { Membership } from './membership'

export interface Member {
  isDeleted?: boolean
  /** @nullable */
  deletedAtUtc?: string | null
  id?: string
  firstName?: string
  lastName?: string
  email?: string
  /** @nullable */
  phoneNumber?: string | null
  dateOfBirth?: string
  createdAtUtc?: string
  memberships?: Membership[]
  accessLogs?: GymAccessLog[]
  fullName?: string
}
