/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PureGym API
 * API for 0-24 gym system
 * OpenAPI spec version: v1
 */
import type { PureGymDomainEntitiesMember } from './pureGymDomainEntitiesMember'
import type { PureGymDomainEntitiesMembership } from './pureGymDomainEntitiesMembership'
import type { PureGymDomainEnumsAccessResult } from './pureGymDomainEnumsAccessResult'

export interface PureGymDomainEntitiesGymAccessLog {
  id?: string
  memberId?: string
  /** @nullable */
  membershipId?: string | null
  accessedAtUtc?: string
  result?: PureGymDomainEnumsAccessResult
  member?: PureGymDomainEntitiesMember
  membership?: PureGymDomainEntitiesMembership | null
}
