/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PureGym API
 * API for 0-24 gym system
 * OpenAPI spec version: v1
 */
import type { PureGymDomainEntitiesBaseSoftDeletableEntity } from './pureGymDomainEntitiesBaseSoftDeletableEntity'
import type { PureGymDomainEntitiesGymAccessLog } from './pureGymDomainEntitiesGymAccessLog'
import type { PureGymDomainEntitiesMember } from './pureGymDomainEntitiesMember'
import type { PureGymDomainEntitiesMembershipType } from './pureGymDomainEntitiesMembershipType'
import type { PureGymDomainEnumsMembershipStatus } from './pureGymDomainEnumsMembershipStatus'

export type PureGymDomainEntitiesMembership = PureGymDomainEntitiesBaseSoftDeletableEntity & {
  id?: string
  memberId?: string
  membershipTypeId?: string
  startDateUtc?: string
  endDateUtc?: string
  status?: PureGymDomainEnumsMembershipStatus
  createdAtUtc?: string
  member?: PureGymDomainEntitiesMember
  membershipType?: PureGymDomainEntitiesMembershipType
  accessLogs?: PureGymDomainEntitiesGymAccessLog[]
  daysRemaining?: number
}
