/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PureGym API
 * API for 0-24 gym system
 * OpenAPI spec version: v1
 */

export type PureGymDomainEnumsAccessResult =
  (typeof PureGymDomainEnumsAccessResult)[keyof typeof PureGymDomainEnumsAccessResult]

export const PureGymDomainEnumsAccessResult = {
  Granted: 0,
  DeniedExpired: 1,
  DeniedSuspended: 2,
  DeniedNoMembership: 3,
} as const
