/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PureGym API
 * API for 0-24 gym system
 * OpenAPI spec version: v1
 */
import type { PureGymApplicationModelsError } from './pureGymApplicationModelsError'

export interface PureGymApplicationModelsResult {
  isSuccess?: boolean
  isFailure?: boolean
  error?: PureGymApplicationModelsError
}
