/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PureGym API
 * API for 0-24 gym system
 * OpenAPI spec version: v1
 */
import type { PureGymDomainEntitiesBaseSoftDeletableEntity } from './pureGymDomainEntitiesBaseSoftDeletableEntity'
import type { PureGymDomainEntitiesMembership } from './pureGymDomainEntitiesMembership'

export type PureGymDomainEntitiesMembershipType = PureGymDomainEntitiesBaseSoftDeletableEntity & {
  id?: string
  name?: string
  /** @nullable */
  description?: string | null
  pricePerMonth?: number
  durationInDays?: number
  isActive?: boolean
  memberships?: PureGymDomainEntitiesMembership[]
}
