/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PureGym API
 * API for 0-24 gym system
 * OpenAPI spec version: v1
 */
import type { PureGymDomainEntitiesBaseSoftDeletableEntity } from './pureGymDomainEntitiesBaseSoftDeletableEntity'
import type { PureGymDomainEntitiesGymAccessLog } from './pureGymDomainEntitiesGymAccessLog'
import type { PureGymDomainEntitiesMembership } from './pureGymDomainEntitiesMembership'

export type PureGymDomainEntitiesMember = PureGymDomainEntitiesBaseSoftDeletableEntity & {
  id?: string
  firstName?: string
  lastName?: string
  email?: string
  /** @nullable */
  phoneNumber?: string | null
  dateOfBirth?: string
  createdAtUtc?: string
  memberships?: PureGymDomainEntitiesMembership[]
  accessLogs?: PureGymDomainEntitiesGymAccessLog[]
  fullName?: string
}
