/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PureGym API
 * API for 0-24 gym system
 * OpenAPI spec version: v1
 */
import type { PureGymApplicationFeaturesGymAccessEnterGymResponse } from './pureGymApplicationFeaturesGymAccessEnterGymResponse'
import type { PureGymApplicationModelsResult } from './pureGymApplicationModelsResult'

export type PureGymApplicationModelsResultOfResponse2 = PureGymApplicationModelsResult & {
  value?: PureGymApplicationFeaturesGymAccessEnterGymResponse | null
}
