/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PureGym API
 * API for 0-24 gym system
 * OpenAPI spec version: v1
 */

export interface PureGymApplicationFeaturesAuthenticationRegisterCommand {
  email?: string
  password?: string
  firstName?: string
  lastName?: string
  dateOfBirth?: string
  /** @nullable */
  phoneNumber?: string | null
}
