/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PureGym API
 * API for 0-24 gym system
 * OpenAPI spec version: v1
 */

export type PureGymDomainEnumsMembershipStatus =
  (typeof PureGymDomainEnumsMembershipStatus)[keyof typeof PureGymDomainEnumsMembershipStatus]

export const PureGymDomainEnumsMembershipStatus = {
  Active: 0,
  Expired: 1,
  Cancelled: 2,
  Suspended: 3,
} as const
