/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PureGym API
 * API for 0-24 gym system
 * OpenAPI spec version: v1
 */
import type { PureGymDomainEntitiesMember } from './pureGymDomainEntitiesMember'

export interface PureGymApplicationFeaturesCommonListQueryOfMember {
  items?: PureGymDomainEntitiesMember[]
  totalCount?: number
}
