/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PureGym API
 * API for 0-24 gym system
 * OpenAPI spec version: v1
 */
import type { PureGymDomainEntitiesGymAccessLog } from './pureGymDomainEntitiesGymAccessLog'

export interface PureGymApplicationFeaturesCommonListQueryOfGymAccessLog {
  items?: PureGymDomainEntitiesGymAccessLog[]
  totalCount?: number
}
