/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PureGym API
 * API for 0-24 gym system
 * OpenAPI spec version: v1
 */

export interface RequestEntryQRResponse {
  memberId?: string
  /** @nullable */
  entryCode?: string | null
  /** @nullable */
  expiry?: string | null
}
