/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PureGym API
 * API for 0-24 gym system
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery,
  type DataTag,
  type DefinedInitialDataOptions,
  type DefinedUseQueryResult,
  type MutationFunction,
  type QueryClient,
  type QueryFunction,
  type QueryKey,
  type UndefinedInitialDataOptions,
  type UseMutationOptions,
  type UseMutationResult,
  type UseQueryOptions,
  type UseQueryResult,
} from '@tanstack/react-query'

import { axiosInstance, type BodyType, type ErrorType } from '../lib/api-client'
import type {
  PureGymApplicationFeaturesAuthenticationLoginCommand,
  PureGymApplicationFeaturesAuthenticationLoginResponse,
  PureGymApplicationFeaturesAuthenticationRegisterCommand,
  PureGymApplicationFeaturesAuthenticationRegisterResponse,
  PureGymApplicationFeaturesCommonListQueryOfGymAccessLog,
  PureGymApplicationFeaturesCommonListQueryOfMember,
  PureGymApplicationFeaturesCommonListQueryOfMembership,
  PureGymApplicationFeaturesCommonListQueryOfMembershipType,
  PureGymApplicationFeaturesGymAccessEnterGymRequest,
  PureGymApplicationFeaturesGymAccessRequestEntryQRResponse,
  PureGymApplicationFeaturesMembershipAddMembershipRequest,
  PureGymApplicationModelsResultOfResponse,
  PureGymApplicationModelsResultOfResponse2,
} from './schemas'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Returns a list of all active (non-deleted) members.
 * @summary List all members
 */
export const pureGymWebAPIFeaturesMembersListMembersEndpoint = (
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<PureGymApplicationFeaturesCommonListQueryOfMember>(
    { url: `/api/members`, method: 'GET', signal },
    options,
  )
}

export const getPureGymWebAPIFeaturesMembersListMembersEndpointQueryKey = () => {
  return [`/api/members`] as const
}

export const getPureGymWebAPIFeaturesMembersListMembersEndpointQueryOptions = <
  TData = Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembersListMembersEndpoint>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembersListMembersEndpoint>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof axiosInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getPureGymWebAPIFeaturesMembersListMembersEndpointQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembersListMembersEndpoint>>
  > = ({ signal }) => pureGymWebAPIFeaturesMembersListMembersEndpoint(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembersListMembersEndpoint>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PureGymWebAPIFeaturesMembersListMembersEndpointQueryResult = NonNullable<
  Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembersListMembersEndpoint>>
>
export type PureGymWebAPIFeaturesMembersListMembersEndpointQueryError = ErrorType<unknown>

export function usePureGymWebAPIFeaturesMembersListMembersEndpoint<
  TData = Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembersListMembersEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembersListMembersEndpoint>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembersListMembersEndpoint>>,
          TError,
          Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembersListMembersEndpoint>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePureGymWebAPIFeaturesMembersListMembersEndpoint<
  TData = Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembersListMembersEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembersListMembersEndpoint>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembersListMembersEndpoint>>,
          TError,
          Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembersListMembersEndpoint>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePureGymWebAPIFeaturesMembersListMembersEndpoint<
  TData = Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembersListMembersEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembersListMembersEndpoint>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all members
 */

export function usePureGymWebAPIFeaturesMembersListMembersEndpoint<
  TData = Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembersListMembersEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembersListMembersEndpoint>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPureGymWebAPIFeaturesMembersListMembersEndpointQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * Creates a new membership for a member based on the specified membership type.
 * @summary Add a membership to a member
 */
export const pureGymWebAPIFeaturesMembershipAddMembershipEndpoint = (
  pureGymApplicationFeaturesMembershipAddMembershipRequest: BodyType<PureGymApplicationFeaturesMembershipAddMembershipRequest>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<PureGymApplicationModelsResultOfResponse>(
    {
      url: `/api/membership`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: pureGymApplicationFeaturesMembershipAddMembershipRequest,
      signal,
    },
    options,
  )
}

export const getPureGymWebAPIFeaturesMembershipAddMembershipEndpointMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipAddMembershipEndpoint>>,
    TError,
    { data: BodyType<PureGymApplicationFeaturesMembershipAddMembershipRequest> },
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipAddMembershipEndpoint>>,
  TError,
  { data: BodyType<PureGymApplicationFeaturesMembershipAddMembershipRequest> },
  TContext
> => {
  const mutationKey = ['pureGymWebAPIFeaturesMembershipAddMembershipEndpoint']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipAddMembershipEndpoint>>,
    { data: BodyType<PureGymApplicationFeaturesMembershipAddMembershipRequest> }
  > = (props) => {
    const { data } = props ?? {}

    return pureGymWebAPIFeaturesMembershipAddMembershipEndpoint(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PureGymWebAPIFeaturesMembershipAddMembershipEndpointMutationResult = NonNullable<
  Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipAddMembershipEndpoint>>
>
export type PureGymWebAPIFeaturesMembershipAddMembershipEndpointMutationBody =
  BodyType<PureGymApplicationFeaturesMembershipAddMembershipRequest>
export type PureGymWebAPIFeaturesMembershipAddMembershipEndpointMutationError = ErrorType<unknown>

/**
 * @summary Add a membership to a member
 */
export const usePureGymWebAPIFeaturesMembershipAddMembershipEndpoint = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipAddMembershipEndpoint>>,
      TError,
      { data: BodyType<PureGymApplicationFeaturesMembershipAddMembershipRequest> },
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipAddMembershipEndpoint>>,
  TError,
  { data: BodyType<PureGymApplicationFeaturesMembershipAddMembershipRequest> },
  TContext
> => {
  return useMutation(
    getPureGymWebAPIFeaturesMembershipAddMembershipEndpointMutationOptions(options),
    queryClient,
  )
}

/**
 * Returns a list of all active (non-deleted) memberships.
 * @summary List all memberships
 */
export const pureGymWebAPIFeaturesMembershipListMembershipsEndpoint = (
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<PureGymApplicationFeaturesCommonListQueryOfMembership>(
    { url: `/api/memberships`, method: 'GET', signal },
    options,
  )
}

export const getPureGymWebAPIFeaturesMembershipListMembershipsEndpointQueryKey = () => {
  return [`/api/memberships`] as const
}

export const getPureGymWebAPIFeaturesMembershipListMembershipsEndpointQueryOptions = <
  TData = Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipListMembershipsEndpoint>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipListMembershipsEndpoint>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof axiosInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getPureGymWebAPIFeaturesMembershipListMembershipsEndpointQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipListMembershipsEndpoint>>
  > = ({ signal }) => pureGymWebAPIFeaturesMembershipListMembershipsEndpoint(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipListMembershipsEndpoint>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PureGymWebAPIFeaturesMembershipListMembershipsEndpointQueryResult = NonNullable<
  Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipListMembershipsEndpoint>>
>
export type PureGymWebAPIFeaturesMembershipListMembershipsEndpointQueryError = ErrorType<unknown>

export function usePureGymWebAPIFeaturesMembershipListMembershipsEndpoint<
  TData = Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipListMembershipsEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipListMembershipsEndpoint>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipListMembershipsEndpoint>>,
          TError,
          Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipListMembershipsEndpoint>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePureGymWebAPIFeaturesMembershipListMembershipsEndpoint<
  TData = Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipListMembershipsEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipListMembershipsEndpoint>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipListMembershipsEndpoint>>,
          TError,
          Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipListMembershipsEndpoint>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePureGymWebAPIFeaturesMembershipListMembershipsEndpoint<
  TData = Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipListMembershipsEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipListMembershipsEndpoint>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all memberships
 */

export function usePureGymWebAPIFeaturesMembershipListMembershipsEndpoint<
  TData = Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipListMembershipsEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipListMembershipsEndpoint>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions =
    getPureGymWebAPIFeaturesMembershipListMembershipsEndpointQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * Returns a list of all active (non-deleted) membership types.
 * @summary List all membership types
 */
export const pureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpoint = (
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<PureGymApplicationFeaturesCommonListQueryOfMembershipType>(
    { url: `/api/membership-types`, method: 'GET', signal },
    options,
  )
}

export const getPureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpointQueryKey = () => {
  return [`/api/membership-types`] as const
}

export const getPureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpointQueryOptions = <
  TData = Awaited<
    ReturnType<typeof pureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpoint>
  >,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpoint>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof axiosInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ??
    getPureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpointQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpoint>>
  > = ({ signal }) =>
    pureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpoint(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpoint>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpointQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpoint>>
  >
export type PureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpointQueryError =
  ErrorType<unknown>

export function usePureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpoint<
  TData = Awaited<
    ReturnType<typeof pureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpoint>
  >,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpoint>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof pureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpoint>
          >,
          TError,
          Awaited<
            ReturnType<typeof pureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpoint>
          >
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpoint<
  TData = Awaited<
    ReturnType<typeof pureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpoint>
  >,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpoint>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof pureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpoint>
          >,
          TError,
          Awaited<
            ReturnType<typeof pureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpoint>
          >
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpoint<
  TData = Awaited<
    ReturnType<typeof pureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpoint>
  >,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpoint>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all membership types
 */

export function usePureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpoint<
  TData = Awaited<
    ReturnType<typeof pureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpoint>
  >,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpoint>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions =
    getPureGymWebAPIFeaturesMembershipTypesListMembershipTypesEndpointQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * Records an attempt by a member to enter the gym and returns whether access was granted.
 * @summary Record a gym entry attempt
 */
export const pureGymWebAPIFeaturesGymAccessEnterGymEndpoint = (
  pureGymApplicationFeaturesGymAccessEnterGymRequest: BodyType<PureGymApplicationFeaturesGymAccessEnterGymRequest>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<PureGymApplicationModelsResultOfResponse2>(
    {
      url: `/api/gym/enter`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: pureGymApplicationFeaturesGymAccessEnterGymRequest,
      signal,
    },
    options,
  )
}

export const getPureGymWebAPIFeaturesGymAccessEnterGymEndpointMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessEnterGymEndpoint>>,
    TError,
    { data: BodyType<PureGymApplicationFeaturesGymAccessEnterGymRequest> },
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessEnterGymEndpoint>>,
  TError,
  { data: BodyType<PureGymApplicationFeaturesGymAccessEnterGymRequest> },
  TContext
> => {
  const mutationKey = ['pureGymWebAPIFeaturesGymAccessEnterGymEndpoint']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessEnterGymEndpoint>>,
    { data: BodyType<PureGymApplicationFeaturesGymAccessEnterGymRequest> }
  > = (props) => {
    const { data } = props ?? {}

    return pureGymWebAPIFeaturesGymAccessEnterGymEndpoint(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PureGymWebAPIFeaturesGymAccessEnterGymEndpointMutationResult = NonNullable<
  Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessEnterGymEndpoint>>
>
export type PureGymWebAPIFeaturesGymAccessEnterGymEndpointMutationBody =
  BodyType<PureGymApplicationFeaturesGymAccessEnterGymRequest>
export type PureGymWebAPIFeaturesGymAccessEnterGymEndpointMutationError = ErrorType<unknown>

/**
 * @summary Record a gym entry attempt
 */
export const usePureGymWebAPIFeaturesGymAccessEnterGymEndpoint = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessEnterGymEndpoint>>,
      TError,
      { data: BodyType<PureGymApplicationFeaturesGymAccessEnterGymRequest> },
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessEnterGymEndpoint>>,
  TError,
  { data: BodyType<PureGymApplicationFeaturesGymAccessEnterGymRequest> },
  TContext
> => {
  return useMutation(
    getPureGymWebAPIFeaturesGymAccessEnterGymEndpointMutationOptions(options),
    queryClient,
  )
}

/**
 * Returns a list of all gym access logs.
 * @summary List all gym access logs
 */
export const pureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpoint = (
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<PureGymApplicationFeaturesCommonListQueryOfGymAccessLog>(
    { url: `/api/gym-access-logs`, method: 'GET', signal },
    options,
  )
}

export const getPureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpointQueryKey = () => {
  return [`/api/gym-access-logs`] as const
}

export const getPureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpointQueryOptions = <
  TData = Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpoint>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpoint>>,
      TError,
      TData
    >
  >
  request?: SecondParameter<typeof axiosInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey =
    queryOptions?.queryKey ?? getPureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpointQueryKey()

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpoint>>
  > = ({ signal }) =>
    pureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpoint(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpoint>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpointQueryResult = NonNullable<
  Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpoint>>
>
export type PureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpointQueryError = ErrorType<unknown>

export function usePureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpoint<
  TData = Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpoint>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpoint>>,
          TError,
          Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpoint>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpoint<
  TData = Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpoint>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpoint>>,
          TError,
          Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpoint>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpoint<
  TData = Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpoint>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all gym access logs
 */

export function usePureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpoint<
  TData = Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpoint>>,
        TError,
        TData
      >
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions =
    getPureGymWebAPIFeaturesGymAccessListGymAccessLogsEndpointQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const pureGymWebAPIFeaturesGymAccessRequestEntryQREndpoint = (
  memberId: string,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<PureGymApplicationFeaturesGymAccessRequestEntryQRResponse>(
    { url: `/api/gym/members/${memberId}/access-keys`, method: 'POST', signal },
    options,
  )
}

export const getPureGymWebAPIFeaturesGymAccessRequestEntryQREndpointMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessRequestEntryQREndpoint>>,
    TError,
    { memberId: string },
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessRequestEntryQREndpoint>>,
  TError,
  { memberId: string },
  TContext
> => {
  const mutationKey = ['pureGymWebAPIFeaturesGymAccessRequestEntryQREndpoint']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessRequestEntryQREndpoint>>,
    { memberId: string }
  > = (props) => {
    const { memberId } = props ?? {}

    return pureGymWebAPIFeaturesGymAccessRequestEntryQREndpoint(memberId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PureGymWebAPIFeaturesGymAccessRequestEntryQREndpointMutationResult = NonNullable<
  Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessRequestEntryQREndpoint>>
>

export type PureGymWebAPIFeaturesGymAccessRequestEntryQREndpointMutationError = ErrorType<void>

export const usePureGymWebAPIFeaturesGymAccessRequestEntryQREndpoint = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessRequestEntryQREndpoint>>,
      TError,
      { memberId: string },
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof pureGymWebAPIFeaturesGymAccessRequestEntryQREndpoint>>,
  TError,
  { memberId: string },
  TContext
> => {
  return useMutation(
    getPureGymWebAPIFeaturesGymAccessRequestEntryQREndpointMutationOptions(options),
    queryClient,
  )
}

/**
 * Authenticates a user with email and password and returns a JWT token.
 * @summary Authenticate a user
 */
export const pureGymWebAPIFeaturesAuthenticationLoginEndpoint = (
  pureGymApplicationFeaturesAuthenticationLoginCommand: BodyType<PureGymApplicationFeaturesAuthenticationLoginCommand>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<PureGymApplicationFeaturesAuthenticationLoginResponse>(
    {
      url: `/api/auth/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: pureGymApplicationFeaturesAuthenticationLoginCommand,
      signal,
    },
    options,
  )
}

export const getPureGymWebAPIFeaturesAuthenticationLoginEndpointMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pureGymWebAPIFeaturesAuthenticationLoginEndpoint>>,
    TError,
    { data: BodyType<PureGymApplicationFeaturesAuthenticationLoginCommand> },
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof pureGymWebAPIFeaturesAuthenticationLoginEndpoint>>,
  TError,
  { data: BodyType<PureGymApplicationFeaturesAuthenticationLoginCommand> },
  TContext
> => {
  const mutationKey = ['pureGymWebAPIFeaturesAuthenticationLoginEndpoint']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pureGymWebAPIFeaturesAuthenticationLoginEndpoint>>,
    { data: BodyType<PureGymApplicationFeaturesAuthenticationLoginCommand> }
  > = (props) => {
    const { data } = props ?? {}

    return pureGymWebAPIFeaturesAuthenticationLoginEndpoint(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PureGymWebAPIFeaturesAuthenticationLoginEndpointMutationResult = NonNullable<
  Awaited<ReturnType<typeof pureGymWebAPIFeaturesAuthenticationLoginEndpoint>>
>
export type PureGymWebAPIFeaturesAuthenticationLoginEndpointMutationBody =
  BodyType<PureGymApplicationFeaturesAuthenticationLoginCommand>
export type PureGymWebAPIFeaturesAuthenticationLoginEndpointMutationError = ErrorType<unknown>

/**
 * @summary Authenticate a user
 */
export const usePureGymWebAPIFeaturesAuthenticationLoginEndpoint = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pureGymWebAPIFeaturesAuthenticationLoginEndpoint>>,
      TError,
      { data: BodyType<PureGymApplicationFeaturesAuthenticationLoginCommand> },
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof pureGymWebAPIFeaturesAuthenticationLoginEndpoint>>,
  TError,
  { data: BodyType<PureGymApplicationFeaturesAuthenticationLoginCommand> },
  TContext
> => {
  return useMutation(
    getPureGymWebAPIFeaturesAuthenticationLoginEndpointMutationOptions(options),
    queryClient,
  )
}

/**
 * Creates a new user account and member profile, then returns a JWT token.
 * @summary Register a new user
 */
export const pureGymWebAPIFeaturesAuthenticationRegisterEndpoint = (
  pureGymApplicationFeaturesAuthenticationRegisterCommand: BodyType<PureGymApplicationFeaturesAuthenticationRegisterCommand>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<PureGymApplicationFeaturesAuthenticationRegisterResponse>(
    {
      url: `/api/auth/register`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: pureGymApplicationFeaturesAuthenticationRegisterCommand,
      signal,
    },
    options,
  )
}

export const getPureGymWebAPIFeaturesAuthenticationRegisterEndpointMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pureGymWebAPIFeaturesAuthenticationRegisterEndpoint>>,
    TError,
    { data: BodyType<PureGymApplicationFeaturesAuthenticationRegisterCommand> },
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof pureGymWebAPIFeaturesAuthenticationRegisterEndpoint>>,
  TError,
  { data: BodyType<PureGymApplicationFeaturesAuthenticationRegisterCommand> },
  TContext
> => {
  const mutationKey = ['pureGymWebAPIFeaturesAuthenticationRegisterEndpoint']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pureGymWebAPIFeaturesAuthenticationRegisterEndpoint>>,
    { data: BodyType<PureGymApplicationFeaturesAuthenticationRegisterCommand> }
  > = (props) => {
    const { data } = props ?? {}

    return pureGymWebAPIFeaturesAuthenticationRegisterEndpoint(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PureGymWebAPIFeaturesAuthenticationRegisterEndpointMutationResult = NonNullable<
  Awaited<ReturnType<typeof pureGymWebAPIFeaturesAuthenticationRegisterEndpoint>>
>
export type PureGymWebAPIFeaturesAuthenticationRegisterEndpointMutationBody =
  BodyType<PureGymApplicationFeaturesAuthenticationRegisterCommand>
export type PureGymWebAPIFeaturesAuthenticationRegisterEndpointMutationError = ErrorType<unknown>

/**
 * @summary Register a new user
 */
export const usePureGymWebAPIFeaturesAuthenticationRegisterEndpoint = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pureGymWebAPIFeaturesAuthenticationRegisterEndpoint>>,
      TError,
      { data: BodyType<PureGymApplicationFeaturesAuthenticationRegisterCommand> },
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof pureGymWebAPIFeaturesAuthenticationRegisterEndpoint>>,
  TError,
  { data: BodyType<PureGymApplicationFeaturesAuthenticationRegisterCommand> },
  TContext
> => {
  return useMutation(
    getPureGymWebAPIFeaturesAuthenticationRegisterEndpointMutationOptions(options),
    queryClient,
  )
}
