/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * PureGym API
 * API for 0-24 gym system
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery,
  type DataTag,
  type DefinedInitialDataOptions,
  type DefinedUseQueryResult,
  type MutationFunction,
  type QueryClient,
  type QueryFunction,
  type QueryKey,
  type UndefinedInitialDataOptions,
  type UseMutationOptions,
  type UseMutationResult,
  type UseQueryOptions,
  type UseQueryResult,
} from '@tanstack/react-query'

import { axiosInstance, type BodyType, type ErrorType } from '../lib/api-client'
import type {
  AddMembershipRequest,
  EnterGymRequest,
  ListQueryOfGymAccessLog,
  ListQueryOfMember,
  ListQueryOfMembership,
  ListQueryOfMembershipType,
  LoginCommand,
  LoginResponse,
  RegisterCommand,
  RegisterResponse,
  RequestEntryQRResponse,
  ResultOfResponse,
  ResultOfResponse2,
} from './schemas'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Returns a list of all active (non-deleted) members.
 * @summary List all members
 */
export const listMembersEndpoint = (
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<ListQueryOfMember>({ url: `/api/members`, method: 'GET', signal }, options)
}

export const getListMembersEndpointQueryKey = () => {
  return [`/api/members`] as const
}

export const getListMembersEndpointQueryOptions = <
  TData = Awaited<ReturnType<typeof listMembersEndpoint>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listMembersEndpoint>>, TError, TData>>
  request?: SecondParameter<typeof axiosInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListMembersEndpointQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listMembersEndpoint>>> = ({ signal }) =>
    listMembersEndpoint(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listMembersEndpoint>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMembersEndpointQueryResult = NonNullable<
  Awaited<ReturnType<typeof listMembersEndpoint>>
>
export type ListMembersEndpointQueryError = ErrorType<unknown>

export function useListMembersEndpoint<
  TData = Awaited<ReturnType<typeof listMembersEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMembersEndpoint>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMembersEndpoint>>,
          TError,
          Awaited<ReturnType<typeof listMembersEndpoint>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMembersEndpoint<
  TData = Awaited<ReturnType<typeof listMembersEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMembersEndpoint>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMembersEndpoint>>,
          TError,
          Awaited<ReturnType<typeof listMembersEndpoint>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMembersEndpoint<
  TData = Awaited<ReturnType<typeof listMembersEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listMembersEndpoint>>, TError, TData>>
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all members
 */

export function useListMembersEndpoint<
  TData = Awaited<ReturnType<typeof listMembersEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listMembersEndpoint>>, TError, TData>>
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListMembersEndpointQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * Creates a new membership for a member based on the specified membership type.
 * @summary Add a membership to a member
 */
export const addMembershipEndpoint = (
  addMembershipRequest: BodyType<AddMembershipRequest>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<ResultOfResponse>(
    {
      url: `/api/membership`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: addMembershipRequest,
      signal,
    },
    options,
  )
}

export const getAddMembershipEndpointMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addMembershipEndpoint>>,
    TError,
    { data: BodyType<AddMembershipRequest> },
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof addMembershipEndpoint>>,
  TError,
  { data: BodyType<AddMembershipRequest> },
  TContext
> => {
  const mutationKey = ['addMembershipEndpoint']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addMembershipEndpoint>>,
    { data: BodyType<AddMembershipRequest> }
  > = (props) => {
    const { data } = props ?? {}

    return addMembershipEndpoint(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type AddMembershipEndpointMutationResult = NonNullable<
  Awaited<ReturnType<typeof addMembershipEndpoint>>
>
export type AddMembershipEndpointMutationBody = BodyType<AddMembershipRequest>
export type AddMembershipEndpointMutationError = ErrorType<unknown>

/**
 * @summary Add a membership to a member
 */
export const useAddMembershipEndpoint = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addMembershipEndpoint>>,
      TError,
      { data: BodyType<AddMembershipRequest> },
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addMembershipEndpoint>>,
  TError,
  { data: BodyType<AddMembershipRequest> },
  TContext
> => {
  return useMutation(getAddMembershipEndpointMutationOptions(options), queryClient)
}

/**
 * Returns a list of all active (non-deleted) memberships.
 * @summary List all memberships
 */
export const listMembershipsEndpoint = (
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<ListQueryOfMembership>(
    { url: `/api/memberships`, method: 'GET', signal },
    options,
  )
}

export const getListMembershipsEndpointQueryKey = () => {
  return [`/api/memberships`] as const
}

export const getListMembershipsEndpointQueryOptions = <
  TData = Awaited<ReturnType<typeof listMembershipsEndpoint>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listMembershipsEndpoint>>, TError, TData>
  >
  request?: SecondParameter<typeof axiosInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListMembershipsEndpointQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listMembershipsEndpoint>>> = ({
    signal,
  }) => listMembershipsEndpoint(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listMembershipsEndpoint>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMembershipsEndpointQueryResult = NonNullable<
  Awaited<ReturnType<typeof listMembershipsEndpoint>>
>
export type ListMembershipsEndpointQueryError = ErrorType<unknown>

export function useListMembershipsEndpoint<
  TData = Awaited<ReturnType<typeof listMembershipsEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMembershipsEndpoint>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMembershipsEndpoint>>,
          TError,
          Awaited<ReturnType<typeof listMembershipsEndpoint>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMembershipsEndpoint<
  TData = Awaited<ReturnType<typeof listMembershipsEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMembershipsEndpoint>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMembershipsEndpoint>>,
          TError,
          Awaited<ReturnType<typeof listMembershipsEndpoint>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMembershipsEndpoint<
  TData = Awaited<ReturnType<typeof listMembershipsEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMembershipsEndpoint>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all memberships
 */

export function useListMembershipsEndpoint<
  TData = Awaited<ReturnType<typeof listMembershipsEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMembershipsEndpoint>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListMembershipsEndpointQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * Returns a list of all active (non-deleted) membership types.
 * @summary List all membership types
 */
export const listMembershipTypesEndpoint = (
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<ListQueryOfMembershipType>(
    { url: `/api/membership-types`, method: 'GET', signal },
    options,
  )
}

export const getListMembershipTypesEndpointQueryKey = () => {
  return [`/api/membership-types`] as const
}

export const getListMembershipTypesEndpointQueryOptions = <
  TData = Awaited<ReturnType<typeof listMembershipTypesEndpoint>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listMembershipTypesEndpoint>>, TError, TData>
  >
  request?: SecondParameter<typeof axiosInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListMembershipTypesEndpointQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listMembershipTypesEndpoint>>> = ({
    signal,
  }) => listMembershipTypesEndpoint(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listMembershipTypesEndpoint>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMembershipTypesEndpointQueryResult = NonNullable<
  Awaited<ReturnType<typeof listMembershipTypesEndpoint>>
>
export type ListMembershipTypesEndpointQueryError = ErrorType<unknown>

export function useListMembershipTypesEndpoint<
  TData = Awaited<ReturnType<typeof listMembershipTypesEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMembershipTypesEndpoint>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMembershipTypesEndpoint>>,
          TError,
          Awaited<ReturnType<typeof listMembershipTypesEndpoint>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMembershipTypesEndpoint<
  TData = Awaited<ReturnType<typeof listMembershipTypesEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMembershipTypesEndpoint>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMembershipTypesEndpoint>>,
          TError,
          Awaited<ReturnType<typeof listMembershipTypesEndpoint>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMembershipTypesEndpoint<
  TData = Awaited<ReturnType<typeof listMembershipTypesEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMembershipTypesEndpoint>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all membership types
 */

export function useListMembershipTypesEndpoint<
  TData = Awaited<ReturnType<typeof listMembershipTypesEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listMembershipTypesEndpoint>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListMembershipTypesEndpointQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * Records an attempt by a member to enter the gym and returns whether access was granted.
 * @summary Record a gym entry attempt
 */
export const enterGymEndpoint = (
  enterGymRequest: BodyType<EnterGymRequest>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<ResultOfResponse2>(
    {
      url: `/api/gym/enter`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: enterGymRequest,
      signal,
    },
    options,
  )
}

export const getEnterGymEndpointMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof enterGymEndpoint>>,
    TError,
    { data: BodyType<EnterGymRequest> },
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof enterGymEndpoint>>,
  TError,
  { data: BodyType<EnterGymRequest> },
  TContext
> => {
  const mutationKey = ['enterGymEndpoint']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof enterGymEndpoint>>,
    { data: BodyType<EnterGymRequest> }
  > = (props) => {
    const { data } = props ?? {}

    return enterGymEndpoint(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type EnterGymEndpointMutationResult = NonNullable<
  Awaited<ReturnType<typeof enterGymEndpoint>>
>
export type EnterGymEndpointMutationBody = BodyType<EnterGymRequest>
export type EnterGymEndpointMutationError = ErrorType<unknown>

/**
 * @summary Record a gym entry attempt
 */
export const useEnterGymEndpoint = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof enterGymEndpoint>>,
      TError,
      { data: BodyType<EnterGymRequest> },
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof enterGymEndpoint>>,
  TError,
  { data: BodyType<EnterGymRequest> },
  TContext
> => {
  return useMutation(getEnterGymEndpointMutationOptions(options), queryClient)
}

/**
 * Returns a list of all gym access logs.
 * @summary List all gym access logs
 */
export const listGymAccessLogsEndpoint = (
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<ListQueryOfGymAccessLog>(
    { url: `/api/gym-access-logs`, method: 'GET', signal },
    options,
  )
}

export const getListGymAccessLogsEndpointQueryKey = () => {
  return [`/api/gym-access-logs`] as const
}

export const getListGymAccessLogsEndpointQueryOptions = <
  TData = Awaited<ReturnType<typeof listGymAccessLogsEndpoint>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listGymAccessLogsEndpoint>>, TError, TData>
  >
  request?: SecondParameter<typeof axiosInstance>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListGymAccessLogsEndpointQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listGymAccessLogsEndpoint>>> = ({
    signal,
  }) => listGymAccessLogsEndpoint(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listGymAccessLogsEndpoint>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListGymAccessLogsEndpointQueryResult = NonNullable<
  Awaited<ReturnType<typeof listGymAccessLogsEndpoint>>
>
export type ListGymAccessLogsEndpointQueryError = ErrorType<unknown>

export function useListGymAccessLogsEndpoint<
  TData = Awaited<ReturnType<typeof listGymAccessLogsEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listGymAccessLogsEndpoint>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGymAccessLogsEndpoint>>,
          TError,
          Awaited<ReturnType<typeof listGymAccessLogsEndpoint>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGymAccessLogsEndpoint<
  TData = Awaited<ReturnType<typeof listGymAccessLogsEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listGymAccessLogsEndpoint>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGymAccessLogsEndpoint>>,
          TError,
          Awaited<ReturnType<typeof listGymAccessLogsEndpoint>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGymAccessLogsEndpoint<
  TData = Awaited<ReturnType<typeof listGymAccessLogsEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listGymAccessLogsEndpoint>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all gym access logs
 */

export function useListGymAccessLogsEndpoint<
  TData = Awaited<ReturnType<typeof listGymAccessLogsEndpoint>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listGymAccessLogsEndpoint>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListGymAccessLogsEndpointQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

export const requestEntryQREndpoint = (
  memberId: string,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<RequestEntryQRResponse>(
    { url: `/api/gym/members/${memberId}/access-keys`, method: 'POST', signal },
    options,
  )
}

export const getRequestEntryQREndpointMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof requestEntryQREndpoint>>,
    TError,
    { memberId: string },
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof requestEntryQREndpoint>>,
  TError,
  { memberId: string },
  TContext
> => {
  const mutationKey = ['requestEntryQREndpoint']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof requestEntryQREndpoint>>,
    { memberId: string }
  > = (props) => {
    const { memberId } = props ?? {}

    return requestEntryQREndpoint(memberId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type RequestEntryQREndpointMutationResult = NonNullable<
  Awaited<ReturnType<typeof requestEntryQREndpoint>>
>

export type RequestEntryQREndpointMutationError = ErrorType<void>

export const useRequestEntryQREndpoint = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof requestEntryQREndpoint>>,
      TError,
      { memberId: string },
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof requestEntryQREndpoint>>,
  TError,
  { memberId: string },
  TContext
> => {
  return useMutation(getRequestEntryQREndpointMutationOptions(options), queryClient)
}

/**
 * Authenticates a user with email and password and returns a JWT token.
 * @summary Authenticate a user
 */
export const loginEndpoint = (
  loginCommand: BodyType<LoginCommand>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<LoginResponse>(
    {
      url: `/api/auth/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: loginCommand,
      signal,
    },
    options,
  )
}

export const getLoginEndpointMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginEndpoint>>,
    TError,
    { data: BodyType<LoginCommand> },
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginEndpoint>>,
  TError,
  { data: BodyType<LoginCommand> },
  TContext
> => {
  const mutationKey = ['loginEndpoint']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginEndpoint>>,
    { data: BodyType<LoginCommand> }
  > = (props) => {
    const { data } = props ?? {}

    return loginEndpoint(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type LoginEndpointMutationResult = NonNullable<Awaited<ReturnType<typeof loginEndpoint>>>
export type LoginEndpointMutationBody = BodyType<LoginCommand>
export type LoginEndpointMutationError = ErrorType<unknown>

/**
 * @summary Authenticate a user
 */
export const useLoginEndpoint = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof loginEndpoint>>,
      TError,
      { data: BodyType<LoginCommand> },
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof loginEndpoint>>,
  TError,
  { data: BodyType<LoginCommand> },
  TContext
> => {
  return useMutation(getLoginEndpointMutationOptions(options), queryClient)
}

/**
 * Creates a new user account and member profile, then returns a JWT token.
 * @summary Register a new user
 */
export const registerEndpoint = (
  registerCommand: BodyType<RegisterCommand>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<RegisterResponse>(
    {
      url: `/api/auth/register`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: registerCommand,
      signal,
    },
    options,
  )
}

export const getRegisterEndpointMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerEndpoint>>,
    TError,
    { data: BodyType<RegisterCommand> },
    TContext
  >
  request?: SecondParameter<typeof axiosInstance>
}): UseMutationOptions<
  Awaited<ReturnType<typeof registerEndpoint>>,
  TError,
  { data: BodyType<RegisterCommand> },
  TContext
> => {
  const mutationKey = ['registerEndpoint']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registerEndpoint>>,
    { data: BodyType<RegisterCommand> }
  > = (props) => {
    const { data } = props ?? {}

    return registerEndpoint(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type RegisterEndpointMutationResult = NonNullable<
  Awaited<ReturnType<typeof registerEndpoint>>
>
export type RegisterEndpointMutationBody = BodyType<RegisterCommand>
export type RegisterEndpointMutationError = ErrorType<unknown>

/**
 * @summary Register a new user
 */
export const useRegisterEndpoint = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof registerEndpoint>>,
      TError,
      { data: BodyType<RegisterCommand> },
      TContext
    >
    request?: SecondParameter<typeof axiosInstance>
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof registerEndpoint>>,
  TError,
  { data: BodyType<RegisterCommand> },
  TContext
> => {
  return useMutation(getRegisterEndpointMutationOptions(options), queryClient)
}
