using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace FitNetClean.SourceGenerators;

[Generator]
public class SettingsRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (s, _) => s is ClassDeclarationSyntax || s is RecordDeclarationSyntax,
                transform: (ctx, _) => GetSettableType(ctx))
            .Where(m => m != null);

        context.RegisterSourceOutput(classes.Collect(), (spc, classNames) =>
        {
            var code = GenerateCode(classNames);
            spc.AddSource("GeneratedSettingsExtensions.g.cs", SourceText.From(code, Encoding.UTF8));
        });
    }

    private string GetSettableType(GeneratorSyntaxContext ctx)
    {
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol;
        if (symbol == null) return null;

        if (symbol.AllInterfaces.Any(i => i.Name == "ISettings"))
        {
            return symbol.ToDisplayString();
        }
        return null;
    }

    private string GenerateCode(ImmutableArray<string> classNames)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.Configuration;");
        sb.AppendLine("namespace FitNetClean.Infrastructure;");
        sb.AppendLine("public static class GeneratedSettingsExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddGeneratedSettings(this IServiceCollection services, IConfiguration configuration)");
        sb.AppendLine("    {");

        foreach (var className in classNames)
        {
            if (string.IsNullOrEmpty(className)) continue;

            sb.AppendLine($@"        services.AddOptions<{className}>()
            .Bind(configuration.GetSection({className}.SectionName))
            .ValidateDataAnnotations()
            .ValidateOnStart();");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}