using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace PureGym.SourceGenerators;

[Generator]
public class SettingsRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var settingsClasses = context.CompilationProvider.Select((compilation, token) =>
        {
            var markerSymbol = compilation.GetTypeByMetadataName("PureGym.SharedKernel.IAssemblyMarker");
            var iSettingsSymbol = compilation.GetTypeByMetadataName("PureGym.SharedKernel.Interfaces.ISettings");

            if (markerSymbol == null || iSettingsSymbol == null)
                return ImmutableArray<string>.Empty;

            var targetAssembly = markerSymbol.ContainingAssembly;

            var foundClasses = ImmutableArray.CreateBuilder<string>();
            ScanNamespace(targetAssembly.GlobalNamespace, iSettingsSymbol, foundClasses);

            return foundClasses.ToImmutable();
        });

        context.RegisterSourceOutput(settingsClasses, (spc, classes) =>
        {
            if (classes.IsDefaultOrEmpty) return;

            var code = GenerateCode(classes, "PureGym.Infrastructure");
            spc.AddSource("GeneratedSettingsExtensions.g.cs", SourceText.From(code, Encoding.UTF8));
        });
    }

    private void ScanNamespace(INamespaceSymbol namespaceSymbol, INamedTypeSymbol interfaceSymbol, ImmutableArray<string>.Builder results)
    {
        foreach (var member in namespaceSymbol.GetMembers())
        {
            if (member is INamespaceSymbol subNamespace)
            {
                ScanNamespace(subNamespace, interfaceSymbol, results);
            }
            else if (member is INamedTypeSymbol typeSymbol)
            {
                if (typeSymbol.TypeKind == TypeKind.Class && !typeSymbol.IsAbstract &&
                    typeSymbol.AllInterfaces.Contains(interfaceSymbol, SymbolEqualityComparer.Default))
                {
                    results.Add(typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                }
            }
        }
    }
    private string GenerateCode(ImmutableArray<string> classNames, string targetNamespace)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.Configuration;");
        sb.AppendLine("using Microsoft.Extensions.Options;");

        sb.AppendLine($"namespace {targetNamespace};");

        sb.AppendLine("public static class GeneratedSettingsExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddGeneratedSettings(this IServiceCollection services, IConfiguration configuration)");
        sb.AppendLine("    {");

        foreach (var className in classNames)
        {
            sb.AppendLine($@"        // Register Options
        services.AddOptions<{className}>()
            .Bind(configuration.GetSection({className}.SectionName))
            .ValidateDataAnnotations()
            .ValidateOnStart();");

            sb.AppendLine($@"        // Register Singleton
        services.AddSingleton(sp => 
            sp.GetRequiredService<IOptions<{className}>>().Value);");

            sb.AppendLine();
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}